# -*- coding: utf-8 -*-
"""ZERO_SHOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jii_qGYQ0shp2g8Bm7_LAcaFUw5TN8BW
"""

import base64
import requests

# OpenAI API Key
api_key = "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"

# Function to encode the image
def encode_image(image_path):
  with open(image_path, "rb") as image_file:
    return base64.b64encode(image_file.read()).decode('utf-8')

# Path to your image
image_path = "/content/SNE_968729.jpg"

# Getting the base64 string
base64_image = encode_image(image_path)

headers = {
  "Content-Type": "application/json",
  "Authorization": f"Bearer {api_key}"
}

payload = {
  "model": "gpt-4-vision-preview",
  "messages": [
      {"role": "user",
      "content": [
        {
          "type": "text",
          "text": "Identify the blood cell type in this image:"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": f"data:image/jpeg;base64,{base64_image}"
          }
        }
      ]
    }
  ],
  "max_tokens": 2000,
  "temperature": 0,
  "top_p": 0
}

response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload)

print(response.json())